import { AsyncActionButton } from "@/components/shared/async-action-button";
import { StatusBadge } from "@/components/shared/status-badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { getIssues } from "@/lib/data";
import { toPercent } from "@/lib/presentation";

export const dynamic = "force-dynamic";

type IssueRow = {
  id: string;
  number: number;
  title: string;
  status: string;
  labels: string[];
  assignees: string[];
  priority: string;
  aiRecommendedAssignee?: string | null;
  aiRiskScore?: number | null;
  repository: { fullName: string };
};

export default async function IssuesPage() {
  const issues = (await getIssues()) as IssueRow[];
  const firstRepo = issues[0]?.repository.fullName;

  return (
    <div className="space-y-4">
      <Card>
        <CardHeader className="flex flex-row items-start justify-between gap-4">
          <div>
            <CardTitle>Issues</CardTitle>
            <p className="mt-1 text-sm text-white/62">Create an issue from AI-generated task framing.</p>
          </div>
          {firstRepo ? (
            <AsyncActionButton
              endpoint="/api/github/issues/create"
              label="Create AI-Generated GitHub Issue"
              pendingLabel="Creating issue..."
              payload={{
                repoFullName: firstRepo,
                title: "AI Task: Add QA safeguards for release readiness",
                body: "Generated by DevPilot AI.\n\nAcceptance Criteria:\n- Add release gate checks\n- Add deployment risk validation",
                labels: ["ai-generated", "qa"],
                assignees: [],
              }}
            />
          ) : null}
        </CardHeader>
      </Card>

      <Card>
        <CardContent className="pt-6">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Title</TableHead>
                <TableHead>Repo</TableHead>
                <TableHead>Status</TableHead>
                <TableHead>Labels</TableHead>
                <TableHead>Assignees</TableHead>
                <TableHead>Priority</TableHead>
                <TableHead>AI Recommended Assignee</TableHead>
                <TableHead>AI Risk Score</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {issues.map((issue) => (
                <TableRow key={issue.id}>
                  <TableCell className="font-medium text-white">#{issue.number} {issue.title}</TableCell>
                  <TableCell>{issue.repository.fullName}</TableCell>
                  <TableCell><StatusBadge value={issue.status} /></TableCell>
                  <TableCell>{issue.labels.join(", ") || "-"}</TableCell>
                  <TableCell>{issue.assignees.join(", ") || "Unassigned"}</TableCell>
                  <TableCell><StatusBadge value={issue.priority} /></TableCell>
                  <TableCell>{issue.aiRecommendedAssignee ?? "N/A"}</TableCell>
                  <TableCell>{toPercent(issue.aiRiskScore)}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}
