const UserRole = {
  MANAGER: "MANAGER",
} as const;

const ProjectStatus = {
  IN_PROGRESS: "IN_PROGRESS",
  QA: "QA",
} as const;

const Priority = {
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  CRITICAL: "CRITICAL",
} as const;

const TaskStatus = {
  TODO: "TODO",
  IN_PROGRESS: "IN_PROGRESS",
  BLOCKED: "BLOCKED",
} as const;

const IssueState = {
  OPEN: "OPEN",
} as const;

const PRState = {
  OPEN: "OPEN",
  MERGED: "MERGED",
} as const;

const DeploymentState = {
  READY: "READY",
  ERROR: "ERROR",
} as const;

const now = new Date();
const hoursAgo = (n: number) => new Date(now.getTime() - n * 60 * 60 * 1000);
const daysAgo = (n: number) => new Date(now.getTime() - n * 24 * 60 * 60 * 1000);

export const demoIds = {
  organization: "org_demo_1",
  user: "user_demo_admin",
  developers: {
    michael: "dev_michael",
    narendra: "dev_narendra",
    peculiar: "dev_peculiar",
  },
  repositories: {
    seo: "repo_seo_dashboard",
    marketing: "repo_marketing_builder",
    aiOps: "repo_aiops",
  },
  vercelProjects: {
    seo: "vercel_project_seo",
    marketing: "vercel_project_marketing",
  },
  projects: {
    seo: "project_seo_dashboard",
    marketing: "project_marketing_builder",
  },
};

export const demoOrganization = {
  id: demoIds.organization,
  name: "DevPilot Internal",
  createdAt: daysAgo(30),
  updatedAt: hoursAgo(4),
};

export const demoUser = {
  id: demoIds.user,
  name: "Engineering Manager",
  email: "manager@devpilot.ai",
  image: null,
  role: UserRole.MANAGER,
  organizationId: demoIds.organization,
  createdAt: daysAgo(20),
  updatedAt: hoursAgo(8),
};

export const demoDevelopers = [
  {
    id: demoIds.developers.michael,
    organizationId: demoIds.organization,
    name: "Michael",
    email: "michael@devpilot.ai",
    githubUsername: "michael-api",
    role: "Backend/API Engineer",
    strengths: ["Node.js", "PostgreSQL", "API reliability"],
    currentCapacity: 82,
    isActive: true,
    createdAt: daysAgo(50),
    updatedAt: hoursAgo(2),
  },
  {
    id: demoIds.developers.narendra,
    organizationId: demoIds.organization,
    name: "Narendra",
    email: "narendra@devpilot.ai",
    githubUsername: "narendra-next",
    role: "Frontend Engineer",
    strengths: ["Next.js", "TypeScript", "UI architecture"],
    currentCapacity: 68,
    isActive: true,
    createdAt: daysAgo(44),
    updatedAt: hoursAgo(3),
  },
  {
    id: demoIds.developers.peculiar,
    organizationId: demoIds.organization,
    name: "Peculiar",
    email: "peculiar@devpilot.ai",
    githubUsername: "peculiar-qa",
    role: "QA / Project Coordination",
    strengths: ["QA design", "Release coordination", "Regression testing"],
    currentCapacity: 75,
    isActive: true,
    createdAt: daysAgo(40),
    updatedAt: hoursAgo(1),
  },
];

export const demoRepositories = [
  {
    id: demoIds.repositories.seo,
    organizationId: demoIds.organization,
    githubId: "gh_repo_1001",
    name: "client-seo-dashboard",
    fullName: "devpilot/client-seo-dashboard",
    owner: "devpilot",
    defaultBranch: "main",
    url: "https://github.com/devpilot/client-seo-dashboard",
    language: "TypeScript",
    isPrivate: true,
    createdAt: daysAgo(35),
    updatedAt: hoursAgo(6),
  },
  {
    id: demoIds.repositories.marketing,
    organizationId: demoIds.organization,
    githubId: "gh_repo_1002",
    name: "marketing-site-builder",
    fullName: "devpilot/marketing-site-builder",
    owner: "devpilot",
    defaultBranch: "main",
    url: "https://github.com/devpilot/marketing-site-builder",
    language: "TypeScript",
    isPrivate: true,
    createdAt: daysAgo(34),
    updatedAt: hoursAgo(10),
  },
  {
    id: demoIds.repositories.aiOps,
    organizationId: demoIds.organization,
    githubId: "gh_repo_1003",
    name: "qa-automation-kits",
    fullName: "devpilot/qa-automation-kits",
    owner: "devpilot",
    defaultBranch: "main",
    url: "https://github.com/devpilot/qa-automation-kits",
    language: "Python",
    isPrivate: true,
    createdAt: daysAgo(22),
    updatedAt: hoursAgo(7),
  },
];

export const demoVercelProjects = [
  {
    id: demoIds.vercelProjects.seo,
    organizationId: demoIds.organization,
    vercelId: "prj_seo_1",
    name: "client-seo-dashboard",
    framework: "nextjs",
    latestDeploymentUrl: "https://client-seo-dashboard-git-main-devpilot.vercel.app",
    createdAt: daysAgo(30),
    updatedAt: hoursAgo(2),
  },
  {
    id: demoIds.vercelProjects.marketing,
    organizationId: demoIds.organization,
    vercelId: "prj_marketing_1",
    name: "marketing-site-builder",
    framework: "nextjs",
    latestDeploymentUrl: "https://marketing-site-builder-git-main-devpilot.vercel.app",
    createdAt: daysAgo(28),
    updatedAt: hoursAgo(5),
  },
];

export const demoProjects = [
  {
    id: demoIds.projects.seo,
    organizationId: demoIds.organization,
    name: "Client SEO Dashboard",
    description: "Multi-tenant SEO operations dashboard for client health and campaigns.",
    status: ProjectStatus.IN_PROGRESS,
    priority: Priority.HIGH,
    businessGoal: "Reduce manual SEO reporting cycles by 70%.",
    targetUser: "SEO account managers",
    repositoryId: demoIds.repositories.seo,
    vercelProjectId: demoIds.vercelProjects.seo,
    createdAt: daysAgo(30),
    updatedAt: hoursAgo(2),
  },
  {
    id: demoIds.projects.marketing,
    organizationId: demoIds.organization,
    name: "Marketing Site Builder",
    description: "Template-driven site generation for campaign launches.",
    status: ProjectStatus.QA,
    priority: Priority.MEDIUM,
    businessGoal: "Ship pages in under 1 hour from campaign request.",
    targetUser: "Growth marketing team",
    repositoryId: demoIds.repositories.marketing,
    vercelProjectId: demoIds.vercelProjects.marketing,
    createdAt: daysAgo(26),
    updatedAt: hoursAgo(9),
  },
];

export const demoIssues = [
  {
    id: "issue_1",
    organizationId: demoIds.organization,
    repositoryId: demoIds.repositories.seo,
    githubIssueId: "gh_issue_2001",
    number: 41,
    title: "Dashboard widgets fail when tenant has no campaigns",
    body: "Null dataset causes cards to throw in render.",
    state: IssueState.OPEN,
    labels: ["bug", "backend"],
    assignees: ["michael-api"],
    priority: Priority.HIGH,
    status: TaskStatus.IN_PROGRESS,
    aiSummary: "Guard null campaign collections before widget aggregation.",
    aiRecommendedAssignee: "Michael",
    aiRiskScore: 0.78,
    blockedReason: null,
    createdAt: daysAgo(6),
    updatedAt: hoursAgo(3),
  },
  {
    id: "issue_2",
    organizationId: demoIds.organization,
    repositoryId: demoIds.repositories.seo,
    githubIssueId: "gh_issue_2002",
    number: 42,
    title: "Add loading and empty states for analytics cards",
    body: "Improve dashboard UX while data fetches.",
    state: IssueState.OPEN,
    labels: ["enhancement", "frontend"],
    assignees: ["narendra-next"],
    priority: Priority.MEDIUM,
    status: TaskStatus.IN_PROGRESS,
    aiSummary: "Current skeleton behavior is inconsistent across card sections.",
    aiRecommendedAssignee: "Narendra",
    aiRiskScore: 0.32,
    blockedReason: null,
    createdAt: daysAgo(4),
    updatedAt: hoursAgo(6),
  },
  {
    id: "issue_3",
    organizationId: demoIds.organization,
    repositoryId: demoIds.repositories.marketing,
    githubIssueId: "gh_issue_2003",
    number: 17,
    title: "Clarify acceptance criteria for onboarding funnel",
    body: "Story is missing expected validation and conversion metrics.",
    state: IssueState.OPEN,
    labels: ["needs-spec"],
    assignees: [],
    priority: Priority.HIGH,
    status: TaskStatus.BLOCKED,
    aiSummary: "Engineering cannot finish without measurable acceptance checks.",
    aiRecommendedAssignee: "Peculiar",
    aiRiskScore: 0.73,
    blockedReason: "Acceptance criteria undefined",
    createdAt: daysAgo(3),
    updatedAt: hoursAgo(16),
  },
  {
    id: "issue_4",
    organizationId: demoIds.organization,
    repositoryId: demoIds.repositories.marketing,
    githubIssueId: "gh_issue_2004",
    number: 18,
    title: "Fix mobile layout regression on pricing section",
    body: "CTA overflows on small screens.",
    state: IssueState.OPEN,
    labels: ["bug", "frontend"],
    assignees: ["narendra-next"],
    priority: Priority.HIGH,
    status: TaskStatus.TODO,
    aiSummary: "Affects conversion funnel on mobile traffic.",
    aiRecommendedAssignee: "Narendra",
    aiRiskScore: 0.61,
    blockedReason: null,
    createdAt: daysAgo(2),
    updatedAt: hoursAgo(8),
  },
  {
    id: "issue_5",
    organizationId: demoIds.organization,
    repositoryId: demoIds.repositories.aiOps,
    githubIssueId: "gh_issue_2005",
    number: 6,
    title: "Backfill flaky E2E test snapshots",
    body: "Snapshot drift causes noisy failures.",
    state: IssueState.OPEN,
    labels: ["qa", "tests"],
    assignees: ["peculiar-qa"],
    priority: Priority.MEDIUM,
    status: TaskStatus.IN_PROGRESS,
    aiSummary: "Stabilizing snapshots will reduce false negatives by ~30%.",
    aiRecommendedAssignee: "Peculiar",
    aiRiskScore: 0.48,
    blockedReason: null,
    createdAt: daysAgo(7),
    updatedAt: hoursAgo(20),
  },
  {
    id: "issue_6",
    organizationId: demoIds.organization,
    repositoryId: demoIds.repositories.seo,
    githubIssueId: "gh_issue_2006",
    number: 45,
    title: "Rate-limit GitHub sync job",
    body: "Avoid secondary API throttling while importing repos.",
    state: IssueState.OPEN,
    labels: ["infra"],
    assignees: [],
    priority: Priority.CRITICAL,
    status: TaskStatus.TODO,
    aiSummary: "Current sync bursts can break data freshness across the dashboard.",
    aiRecommendedAssignee: "Michael",
    aiRiskScore: 0.88,
    blockedReason: null,
    createdAt: daysAgo(1),
    updatedAt: hoursAgo(1),
  },
  {
    id: "issue_7",
    organizationId: demoIds.organization,
    repositoryId: demoIds.repositories.marketing,
    githubIssueId: "gh_issue_2007",
    number: 19,
    title: "Add campaign template autosave",
    body: "Users lose edits when navigating away.",
    state: IssueState.OPEN,
    labels: ["feature"],
    assignees: ["narendra-next"],
    priority: Priority.MEDIUM,
    status: TaskStatus.TODO,
    aiSummary: "High UX impact with low implementation complexity.",
    aiRecommendedAssignee: "Narendra",
    aiRiskScore: 0.29,
    blockedReason: null,
    createdAt: daysAgo(5),
    updatedAt: hoursAgo(12),
  },
  {
    id: "issue_8",
    organizationId: demoIds.organization,
    repositoryId: demoIds.repositories.aiOps,
    githubIssueId: "gh_issue_2008",
    number: 8,
    title: "Create release checklist template for QA",
    body: "Standardize release gates before production deploy.",
    state: IssueState.OPEN,
    labels: ["qa", "process"],
    assignees: ["peculiar-qa"],
    priority: Priority.HIGH,
    status: TaskStatus.TODO,
    aiSummary: "Lack of standardized checklists increases regressions.",
    aiRecommendedAssignee: "Peculiar",
    aiRiskScore: 0.57,
    blockedReason: null,
    createdAt: daysAgo(2),
    updatedAt: hoursAgo(5),
  },
];

export const demoPullRequests = [
  {
    id: "pr_1",
    organizationId: demoIds.organization,
    repositoryId: demoIds.repositories.seo,
    githubPrId: "gh_pr_3001",
    number: 42,
    title: "Refactor billing API retries",
    body: "Adds retry wrapper and error instrumentation.",
    state: PRState.OPEN,
    author: "michael-api",
    branchName: "feature/billing-retries",
    baseBranch: "main",
    changedFiles: 9,
    additions: 280,
    deletions: 77,
    mergeable: false,
    draft: false,
    aiSummary: "Logic is sound but lacks integration tests for retry caps.",
    aiReviewStatus: "REQUEST_CHANGES",
    aiRiskScore: 0.81,
    createdAt: daysAgo(2),
    updatedAt: hoursAgo(3),
  },
  {
    id: "pr_2",
    organizationId: demoIds.organization,
    repositoryId: demoIds.repositories.marketing,
    githubPrId: "gh_pr_3002",
    number: 27,
    title: "Improve dashboard loading states",
    body: "Adds skeleton components and transitions.",
    state: PRState.OPEN,
    author: "narendra-next",
    branchName: "feat/loading-states",
    baseBranch: "main",
    changedFiles: 6,
    additions: 152,
    deletions: 24,
    mergeable: true,
    draft: false,
    aiSummary: "Ready for QA after visual checks on mobile breakpoints.",
    aiReviewStatus: "NEEDS_QA",
    aiRiskScore: 0.34,
    createdAt: daysAgo(1),
    updatedAt: hoursAgo(5),
  },
  {
    id: "pr_3",
    organizationId: demoIds.organization,
    repositoryId: demoIds.repositories.aiOps,
    githubPrId: "gh_pr_3003",
    number: 12,
    title: "Stabilize flaky E2E assertions",
    body: "Introduces deterministic fixtures and retries.",
    state: PRState.OPEN,
    author: "peculiar-qa",
    branchName: "chore/e2e-stability",
    baseBranch: "main",
    changedFiles: 11,
    additions: 220,
    deletions: 96,
    mergeable: true,
    draft: true,
    aiSummary: "Good direction, still missing edge-case assertions for timeout flow.",
    aiReviewStatus: "IN_REVIEW",
    aiRiskScore: 0.52,
    createdAt: daysAgo(3),
    updatedAt: hoursAgo(7),
  },
  {
    id: "pr_4",
    organizationId: demoIds.organization,
    repositoryId: demoIds.repositories.marketing,
    githubPrId: "gh_pr_3004",
    number: 24,
    title: "Fix footer rendering bug",
    body: "Resolves hydration mismatch in footer links.",
    state: PRState.MERGED,
    author: "narendra-next",
    branchName: "fix/footer-hydration",
    baseBranch: "main",
    changedFiles: 3,
    additions: 40,
    deletions: 18,
    mergeable: true,
    draft: false,
    aiSummary: "Low risk fix with regression test coverage.",
    aiReviewStatus: "APPROVED",
    aiRiskScore: 0.11,
    createdAt: daysAgo(6),
    updatedAt: daysAgo(4),
  },
];

export const demoCommits = [
  {
    id: "commit_1",
    organizationId: demoIds.organization,
    repositoryId: demoIds.repositories.seo,
    sha: "abc1234def",
    message: "fix: guard null campaign metrics",
    author: "michael-api",
    url: "https://github.com/devpilot/client-seo-dashboard/commit/abc1234def",
    committedAt: hoursAgo(3),
    createdAt: hoursAgo(3),
  },
  {
    id: "commit_2",
    organizationId: demoIds.organization,
    repositoryId: demoIds.repositories.marketing,
    sha: "def5678ghi",
    message: "feat: add pricing mobile constraints",
    author: "narendra-next",
    url: "https://github.com/devpilot/marketing-site-builder/commit/def5678ghi",
    committedAt: hoursAgo(9),
    createdAt: hoursAgo(9),
  },
  {
    id: "commit_3",
    organizationId: demoIds.organization,
    repositoryId: demoIds.repositories.aiOps,
    sha: "ghi9012jkl",
    message: "test: stabilize e2e fixtures",
    author: "peculiar-qa",
    url: "https://github.com/devpilot/qa-automation-kits/commit/ghi9012jkl",
    committedAt: hoursAgo(14),
    createdAt: hoursAgo(14),
  },
];

export const demoDeployments = [
  {
    id: "dep_1",
    organizationId: demoIds.organization,
    vercelProjectId: demoIds.vercelProjects.seo,
    vercelDeploymentId: "dpl_5001",
    url: "https://client-seo-dashboard-git-main-devpilot.vercel.app",
    state: DeploymentState.READY,
    target: "production",
    branch: "main",
    commitSha: "abc1234def",
    githubPrNumber: 42,
    errorMessage: null,
    aiSummary: "Healthy production deployment.",
    aiRiskScore: 0.16,
    createdAt: hoursAgo(4),
    updatedAt: hoursAgo(4),
  },
  {
    id: "dep_2",
    organizationId: demoIds.organization,
    vercelProjectId: demoIds.vercelProjects.seo,
    vercelDeploymentId: "dpl_5002",
    url: "https://client-seo-dashboard-git-feature-billing-retries-devpilot.vercel.app",
    state: DeploymentState.ERROR,
    target: "preview",
    branch: "feature/billing-retries",
    commitSha: "abc1234def",
    githubPrNumber: 42,
    errorMessage: "Missing environment variable BILLING_API_KEY",
    aiSummary: "Preview failed due to missing env variable required by billing service.",
    aiRiskScore: 0.91,
    createdAt: hoursAgo(2),
    updatedAt: hoursAgo(2),
  },
  {
    id: "dep_3",
    organizationId: demoIds.organization,
    vercelProjectId: demoIds.vercelProjects.marketing,
    vercelDeploymentId: "dpl_5003",
    url: "https://marketing-site-builder-git-feat-loading-states-devpilot.vercel.app",
    state: DeploymentState.READY,
    target: "preview",
    branch: "feat/loading-states",
    commitSha: "def5678ghi",
    githubPrNumber: 27,
    errorMessage: null,
    aiSummary: "Preview is stable and ready for QA pass.",
    aiRiskScore: 0.28,
    createdAt: hoursAgo(6),
    updatedAt: hoursAgo(6),
  },
  {
    id: "dep_4",
    organizationId: demoIds.organization,
    vercelProjectId: demoIds.vercelProjects.marketing,
    vercelDeploymentId: "dpl_5004",
    url: "https://marketing-site-builder-git-main-devpilot.vercel.app",
    state: DeploymentState.ERROR,
    target: "production",
    branch: "main",
    commitSha: "zzz9999",
    githubPrNumber: null,
    errorMessage: "Build failed: Cannot find module '@/lib/tracking'",
    aiSummary: "Production build references missing module after refactor.",
    aiRiskScore: 0.87,
    createdAt: hoursAgo(20),
    updatedAt: hoursAgo(20),
  },
  {
    id: "dep_5",
    organizationId: demoIds.organization,
    vercelProjectId: demoIds.vercelProjects.marketing,
    vercelDeploymentId: "dpl_5005",
    url: "https://marketing-site-builder-git-fix-footer-hydration-devpilot.vercel.app",
    state: DeploymentState.READY,
    target: "preview",
    branch: "fix/footer-hydration",
    commitSha: "footer123",
    githubPrNumber: 24,
    errorMessage: null,
    aiSummary: "Regression fix deployed with healthy checks.",
    aiRiskScore: 0.12,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
];

export const demoDailyPlan = {
  id: "daily_plan_1",
  organizationId: demoIds.organization,
  title: "Today's Engineering Plan",
  summary:
    "Stabilize dashboard release, resolve two deployment failures, and unblock requirements clarity before shipping.",
  priorities: [
    "Fix failed dashboard preview deployment",
    "Review PR #42 and require test coverage",
    "Unblock onboarding acceptance criteria",
    "QA loading-state preview before merge",
  ],
  assignments: [
    "Michael: fix missing BILLING_API_KEY and add retry integration tests",
    "Narendra: finalize loading-state polish and mobile QA fixes",
    "Peculiar: define acceptance criteria for onboarding and run QA pass",
  ],
  blockers: [
    "Missing BILLING_API_KEY in Vercel preview environment",
    "Onboarding funnel ticket missing acceptance criteria",
  ],
  qaItems: [
    "Verify loading states on mobile/tablet",
    "Run regression on billing API retry behavior",
    "Validate onboarding funnel after criteria update",
  ],
  deploymentRisks: [
    "Production marketing build failed due to missing tracking module",
    "Billing preview cannot validate until env var is added",
  ],
  recommendations: [
    "Do not merge PR #42 until integration tests are present",
    "Patch missing tracking import path before next production deploy",
    "Re-run failed deployments immediately after fixes",
  ],
  riskLevel: "High",
  createdAt: hoursAgo(1),
  updatedAt: hoursAgo(1),
};

export const demoQAReviews = [
  {
    id: "qa_review_1",
    organizationId: demoIds.organization,
    pullRequestId: "pr_1",
    deploymentId: "dep_2",
    status: "BLOCK_MERGE",
    summary: "Billing retry PR is missing integration tests and preview is failing.",
    checklist: [
      { item: "Issue addressed", status: "pass" },
      { item: "Automated tests updated", status: "fail" },
      { item: "Preview deployment healthy", status: "fail" },
    ],
    risks: [
      "Retry logic may hide recurring downstream failures",
      "No test asserting max retry boundary",
    ],
    missingTests: [
      "Add integration test for retry cap",
      "Add failure-case test for invalid billing API response",
    ],
    acceptanceCriteriaStatus: "Partial",
    recommendation: "Request changes",
    createdAt: hoursAgo(2),
    updatedAt: hoursAgo(2),
  },
  {
    id: "qa_review_2",
    organizationId: demoIds.organization,
    pullRequestId: "pr_2",
    deploymentId: "dep_3",
    status: "NEEDS_QA",
    summary: "Loading state improvements are good and ready for manual QA signoff.",
    checklist: [
      { item: "Issue addressed", status: "pass" },
      { item: "Automated tests updated", status: "pass" },
      { item: "Preview deployment healthy", status: "pass" },
    ],
    risks: ["Potential animation jank on low-end devices"],
    missingTests: ["Add visual regression snapshots for skeleton components"],
    acceptanceCriteriaStatus: "Mostly Met",
    recommendation: "Needs QA",
    createdAt: hoursAgo(5),
    updatedAt: hoursAgo(5),
  },
];

export const demoTaskAssignments = [
  {
    id: "assignment_1",
    organizationId: demoIds.organization,
    issueId: "issue_1",
    developerId: demoIds.developers.michael,
    status: TaskStatus.IN_PROGRESS,
    reason: "Original author of recent failing billing commits.",
    dueDate: daysAgo(-1),
    createdAt: daysAgo(1),
    updatedAt: hoursAgo(2),
  },
  {
    id: "assignment_2",
    organizationId: demoIds.organization,
    issueId: "issue_2",
    developerId: demoIds.developers.narendra,
    status: TaskStatus.IN_PROGRESS,
    reason: "Frontend owner for dashboard card experience.",
    dueDate: daysAgo(-1),
    createdAt: daysAgo(1),
    updatedAt: hoursAgo(3),
  },
  {
    id: "assignment_3",
    organizationId: demoIds.organization,
    issueId: "issue_5",
    developerId: demoIds.developers.peculiar,
    status: TaskStatus.IN_PROGRESS,
    reason: "QA lead for test stabilization workstream.",
    dueDate: daysAgo(-2),
    createdAt: daysAgo(2),
    updatedAt: hoursAgo(12),
  },
];

export const demoProjectMemories = [
  {
    id: "memory_1",
    organizationId: demoIds.organization,
    projectId: demoIds.projects.seo,
    key: "qa_rules",
    value: {
      requireTestsForBackend: true,
      mustHavePreviewDeployment: true,
      blockMergeOnFailedDeployment: true,
    },
    createdAt: daysAgo(8),
    updatedAt: daysAgo(1),
  },
  {
    id: "memory_2",
    organizationId: demoIds.organization,
    projectId: demoIds.projects.marketing,
    key: "coding_standards",
    value: {
      requiredChecks: ["eslint", "typecheck", "preview-smoke-test"],
      avoidDirectDOMMutation: true,
    },
    createdAt: daysAgo(10),
    updatedAt: daysAgo(2),
  },
];

export const demoActivityLogs = [
  {
    id: "activity_1",
    organizationId: demoIds.organization,
    actor: "System",
    type: "SYNC",
    message: "Imported GitHub repositories and pull requests.",
    metadata: { source: "github" },
    createdAt: hoursAgo(6),
  },
  {
    id: "activity_2",
    organizationId: demoIds.organization,
    actor: "AI",
    type: "DAILY_PLAN",
    message: "Generated daily engineering plan.",
    metadata: { riskLevel: "High" },
    createdAt: hoursAgo(1),
  },
];

export const demoIntegrationCredentials = [
  {
    id: "cred_1",
    organizationId: demoIds.organization,
    provider: "github",
    accessToken: null,
    refreshToken: null,
    installationId: "123456",
    metadata: { connected: false },
    createdAt: daysAgo(6),
    updatedAt: hoursAgo(6),
  },
  {
    id: "cred_2",
    organizationId: demoIds.organization,
    provider: "vercel",
    accessToken: null,
    refreshToken: null,
    installationId: null,
    metadata: { connected: false },
    createdAt: daysAgo(6),
    updatedAt: hoursAgo(6),
  },
];
